- fix in checking is netforking is up.
Changed files:
    news.init -> 1.4

diff --git a/news.init b/news.init
--- a/news.init
+++ b/news.init
@@ -20,7 +20,10 @@
 [ -f /etc/sysconfig/inn ] && . /etc/sysconfig/inn
 
 # Check that networking is up.
-[ "${NETWORKING}" = "no" ] && echo "Error: Networking is down" && exit 0
+if [ "${NETWORKING}" = "no" ]; then
+	echo "WARNING: Networking is down. Inn service can't be runed "
+	exit 1
+fi
 
 # Sanity check
 [ -d /etc/news ] || exit 0
